### ISSUE TITLE
Adding the filter scroll menu into jitsi Meeting

### ISSUE THREAD

**Issue by Yaccoub** [udexon/Phoom#1]
Hi, 
first of all thank you for the effort in the project. I would like to ask you if there is a possibility to integrate Hu Ningxin's OpenCV filtering into the Jitsi Meeting as a toolbar. Thank you in advance.

**Comment by udexon** [comment]
Can you chat using gmail ?

Google Meeet?

My gmail is lsn95r @ gmail.com

There are many issues we can discuss.

I will delete this message after you reply to protect my email.

**Comment by Yaccoub** [comment]
Hi
I have sent you an email. You can delete the post to protect your email.
